version: '2.1'
services:
  balancer:
    container_name: nginx-nodepop
    build: ./balancer/.
    depends_on:
      nodepop-api:
        condition: service_started
    ports:
      - "80:80"
  nodepop-api:
    container_name: nodepop-api
    build: ./.
    depends_on:
      mongo-nodepop:
        condition: service_started
    ports:
      - "3000"
    networks:
      - mongodb
  mongo-nodepop:
    container_name: mongo-nodepop
    image: mongo
    volumes:
      - "./db:/data/db"
    command: mongod
    ports:
      - "27017"
    networks:
      - mongodb
networks:
  mongodb: